### ISSUE TITLE
Error in match-syntax.md

### ISSUE THREAD

**Issue by aliraza0337** [CCI-MOC/flocx#22]
Some of the example are not correct for example the JMESPath expression "system_vendor.manufacturer" isn't valid instead it should be "inventory.system_vendor.manufacturer"

Also null is not python syntax so either use None or make null a string.

**Comment by larsks** [comment]
> "system_vendor.manufacturer" isn't valid instead it should be "inventory.system_vendor.manufacturer"

Thanks, fixed!

> Also null is not python syntax so either use None or make null a string.

Those are actually JSON representations, so `null` is valid.
